---
- name: docker | remove legacy package
  apt: name={{ item }} state=absent
  with_items:
    - docker 
    - docker-engine
    - lxc-docker

- name: docker | install prereqs
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=600
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Ensure curl is present (on older systems without SNI).
  package: name=curl state=present
  when: add_repository_key|failed

- name: Add Docker apt key (alternative for older systems without SNI).
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: no
  when: add_repository_key|failed

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes
  notify:
    -docker-apt-get-update

- meta: flush_handlers

- name: Install Docker.
  package: name={{ docker_package }} state=present

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- name: docker | configure
  include: configure.yml
  when: ansible_distribution_version in [ "14.04" ]
 
- name: docker | configure
  include: configure-sysd.yml
  when: ansible_distribution_version in [ "16.04", "16.10" ]

- meta: flush_handlers

- name: Add user(s) to docker group
  user: 
      name={{ item }} 
      groups=docker 
      append=yes
  with_items: "{{ docker_users }}"

- name: Create Certificate Directories
  file:
    path: "/etc/docker/certs.d/{{ item.host }}"
    state: directory
  with_items: "{{ docker_certificates }}"

- name: Install Certificates
  copy:
    content: "{{ item.certificate }}"
    dest: "/etc/docker/certs.d/{{ item.host }}/ca.crt"
  with_items: "{{ docker_certificates }}"
  when: docker_certificates is defined
