---
- name: docker | install prereqs
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=600
  with_items:
    - apt-transport-https
    - ca-certificates
    - linux-image-extra-{{ ansible_kernel }}

- name: docker | apt signing key
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
  notify: 'docker-apt-get-update'

- name: docker | apt repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: 'present'
  notify:
  - docker-apt-get-update

- meta: flush_handlers

- name: docker | remove legacy package
  apt: name=lxc-docker state=absent

- name: docker | install
  apt: name=docker-engine state=latest

- name: docker | configure
  include: configure.yml
  when: ansible_distribution_version in [ "14.04" ]
 
- name: docker | configure
  include: configure-sysd.yml
  when: ansible_distribution_version in [ "16.04", "16.10" ]

- meta: flush_handlers

- name: Add user(s) to docker group
  user: 
      name={{ item }} 
      groups=docker 
      append=yes
  with_items: "{{ docker_users }}"

- name: Create Certificate Directories
  file:
    path: "/etc/docker/certs.d/{{ item.host }}"
    state: directory
  with_items: "{{ docker_certificates }}"

- name: Install Certificates
  copy:
    content: "{{ item.certificate }}"
    dest: "/etc/docker/certs.d/{{ item.host }}/ca.crt"
  with_items: "{{ docker_certificates }}"
  when: docker_certificates is defined
